version: "3"

services:
  db:
    image: postgres
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/application
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
