version: "3"

services:
#  db:
#    image: postgres
#    volumes:
#      - ./storage/postgres/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
  web:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/application
    ports:
      - "8000:8000"
    depends_on:
#      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    #    hostname: my-rabbit
    volumes:
      #      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      #      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./storage/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./storage/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
      #    environment:
      #      - RABBITMQ_DEFAULT_USER:rabbitmq
      #      - RABBITMQ_DEFAULT_PASS:rabbitmq
      # The default user is created only if the database does not exist. Therefore the environment variables have no effect if the volume already exists.